### ISSUE TITLE
RuntimeError: get_max_shared_memory_per_block :failed to cudaGetDevice: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by feiwenbo** [CoinCheung/BiSeNet#10]
can you show me the cuda driver version and cuda runtime version what you used ? thanks

**Comment by CoinCheung** [comment]
Hi, 

by running `cat /usr/local/cuda/version.txt`, I get the version message of: `CUDA Version 9.0.176`. Hope this would help.

**Comment by feiwenbo** [comment]
thanks , I use the CUDA 10.0, and the driver version is 410.78, it does not work, this code only run in CUDA 9.0?

**Comment by CoinCheung** [comment]
That can be the reason to this problem, have you ever tried your pytorch1.0? can your pytorch1.0 work well?

**Comment by feiwenbo** [comment]
Yes, my pytorch is 1.0.1,it works well when I run other code, I guess inplace_bn caused this problem. This is  the whole errer code, even if I used the CUDA 9.0,I can not find the reason.
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=34 error=10 : invalid device ordinal
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train()
  File "train.py", line 44, in train
    torch.cuda.set_device(args.local_rank)
  File "/home/feiwenbo/.local/lib/python3.5/site-packages/torch/cuda/__init__.py", line 264, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (10) : invalid device ordinal at /pytorch/torch/csrc/cuda/Module.cpp:34
Traceback (most recent call last):
  File "train.py", line 166, in <module>
    train()
  File "train.py", line 127, in train
    loss.backward()
  File "/home/feiwenbo/.local/lib/python3.5/site-packages/torch/tensor.py", line 102, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/feiwenbo/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
  File "/home/feiwenbo/.local/lib/python3.5/site-packages/torch/autograd/function.py", line 76, in apply
    return self._forward_cls.backward(self, *args)
  File "/home/feiwenbo/.local/lib/python3.5/site-packages/torch/autograd/function.py", line 188, in wrapper
    outputs = fn(ctx, *args)
  File "/media/feiwenbo/1EA2B45DA2B43ADB/BiSeNet_cityscapes/BiSeNet/modules/functions.py", line 208, in backward
    _act_backward(ctx, z, dz)
  File "/media/feiwenbo/1EA2B45DA2B43ADB/BiSeNet_cityscapes/BiSeNet/modules/functions.py", line 70, in _act_backward
    _backend.leaky_relu_backward(x, dx, ctx.slope)
RuntimeError: get_max_shared_memory_per_block :failed to cudaGetDevice: CUDA driver version is insufficient for CUDA runtime version

**Comment by CoinCheung** [comment]
I agree with you, maybe inplace-abn does not support cuda10 currently, or so the version I used. You can see the updates of inplace-abn with [this](https://github.com/mapillary/inplace_abn) link. If there is useful updates, you could replace the associated files with its new version. If that does not work, maybe you could consider other sync-bn implementations.

**Comment by feiwenbo** [comment]
Thanks, I will try it.

**Comment by CoinCheung** [comment]
I am closing this, since this might not be a problem anymore after so much time. Thanks for your interest !!
