### ISSUE TITLE
Images with size 1280x720 doesn't work but 640x480 does

### ISSUE THREAD

**Issue by christka1** [CoinCheung/BiSeNet#132]
Hi!

I'm trying to test the demo of bisenetv2 on my own image. The image that I'm trying to use is of size 1280x720 and gives the error:

RuntimeError: The size of tensor a (90) must match the size of tensor b (92) at non-singleton dimension 2

This does not happen if I resize the image to 640x480 before running it through the network. Are there any limitations regarding the image size and ratio or is something else wrong?

Best regards

**Comment by christka1** [comment]
Solved it.

Since there is a downsampling of 32, the sizes need to be evenly divisible with 32.

**Comment by farmbert** [comment]
Hi!
I have the same issue. Have you managed to train/test images with other ratios? I'm only able to train 2048x1024 or 1024x512, even 640x480 does not work.

**Comment by christka1** [comment]
Hi!
I managed to train the network as long as the width and height of the images are both evenly divisible with 32. You can either resize or crop the images to get this. Remember to do the same operation on the label image as well.

**Comment by farmbert** [comment]
Ok, sorry I just saw that the Error only occurs during the evaluation not training. And there exactly in evaluation.py line 214 `ms_flip = MscEvalV0((0.5,0.75, 1.0, 1.25, 1.5, 1.75), True)` when I edit this line that only one float remains it works but it doesn't matter which and the miou stays the same so I don't know if this is the correct solution?

**Comment by farmbert** [comment]
Here is the log info:

```
save models to ./res/model_final.pth

evaluating the final model
  0%|                                                     | 0/1 [00:00<?, ?it/s]/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s]
single mIOU is: 0.33251574635505676

  0%|                                                     | 0/1 [00:00<?, ?it/s]/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
100%|█████████████████████████████████████████████| 1/1 [00:00<00:00,  2.26it/s]
single scale crop mIOU is: 0.33251574635505676

  0%|                                                     | 0/1 [00:00<?, ?it/s]/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
/shared/thistle/images/val/DJI_0627.jpg
/shared/thistle/annotations/val/DJI_0627.jpg
Traceback (most recent call last):
  File "/home/josres/BiSeNet/robert/tools/train_amp.py", line 319, in <module>
    main()
  File "/home/josres/BiSeNet/robert/tools/train_amp.py", line 315, in main
    train_start()
  File "/home/josres/BiSeNet/robert/tools/train_amp.py", line 291, in train_start
    train()
  File "/home/josres/BiSeNet/robert/tools/train_amp.py", line 273, in train
    heads, mious = eval_model(net, 2, cfg.im_root, cfg.val_im_anns)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "./evaluate.py", line 215, in eval_model
    mIOU = ms_flip(net, dl, 3)#19
  File "./evaluate.py", line 55, in __call__
    logits = net(im_sc)[0]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 332, in forward
    feat_head = self.bga(feat_d, feat_s)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 273, in forward
    left = left1 * torch.sigmoid(right1)
RuntimeError: The size of tensor a (90) must match the size of tensor b (92) at non-singleton dimension 2
  0%|                                                     | 0/1 [00:00<?, ?it/s]
```

**Comment by christka1** [comment]
I think the problem is that one of the scaling factors multiplied by your image size is not evenly divisible with 32. So you have to check that as well and choose which scaling factors that you would like to use for evalution.

**Comment by farmbert** [comment]
Oh, okay that sounds logical. Thanks for the quick help!!!
