### ISSUE TITLE
I got this Error when ran the training code

### ISSUE THREAD

**Issue by Saleh-Gholam-Zadeh** [CoinCheung/BiSeNet#133]
I ran the code like this:
`CUDA_VISIBLE_DEVICES=0  python -m torch.distributed.launch --nproc_per_node=1  tools/train.py --model bisenetv2`

and got the error below:

----------------------------------------------------------------------------------
Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 221, in main
    train()
  File "tools/train.py", line 164, in train
    for it, (im, lb) in enumerate(dl):
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/base_dataset.py", line 45, in __getitem__
    img, label = cv2.imread(impth)[:, :, ::-1], cv2.imread(lbpth, 0)
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/saleh/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/saleh/anaconda3/envs/bisenet/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv2']' returned non-zero exit status 1.

------------------

Can anybody help me with this error?
Thank you in advance

**Comment by CoinCheung** [comment]
Please check the part about your dataset. The problem is likely associated with your path configuration.
