### ISSUE TITLE
copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered.

### ISSUE THREAD

**Issue by 202041600047** [CoinCheung/BiSeNet#160]
Hi,I have a problem:RuntimeError: 
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/tools/train.py", line 226, in <module>
    main()
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/tools/train.py", line 222, in main
    train()
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/tools/train.py", line 173, in train
    loss_pre = criteria_pre(logits, lb)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/ohem_ce_loss.py", line 38, in forward
    loss_hard = loss[loss > self.thresh]
RuntimeError: copy_if failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
How can I solve this problem？thanks

**Comment by CoinCheung** [comment]
Would you please tell me how to reproduce this problem? Did you train your model following the readme?

**Comment by RoboCuper-hujinlei** [comment]
I also encountered the same problem, please help me to answer it, thank you！

**Comment by CoinCheung** [comment]
@RoboCuper-hujinlei What modifications did you made, are you training your model following the default configuration?
