### ISSUE TITLE
assert im.shape[:2] == lb.shape[:2]  AssertionError

### ISSUE THREAD

**Issue by 202041600047** [CoinCheung/BiSeNet#161]
Hi,Thank you for your contribution to this project. I have a question:
  
File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/train.py", line 161, in train
    for it, (im, lb) in enumerate(dl):
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/base_dataset.py", line 48, in __getitem__
    im_lb = self.trans_func(im_lb)
  File "./lib/base_dataset.py", line 71, in __call__
    im_lb = self.trans_func(im_lb)
  File "./lib/transform_cv2.py", line 150, in __call__
    im_lb = comp(im_lb)
  File "./lib/transform_cv2.py", line 27, in __call__
    assert im.shape[:2] == lb.shape[:2]
AssertionError

I don't know how to solve this problem. Can you help me

**Comment by CoinCheung** [comment]
Please tell me what modifications did you make, are you using your own dataset of one-channel images to train?

**Comment by Byronnar** [comment]
> Please tell me what modifications did you make, are you using your own dataset of one-channel images to train?

Bisenetv2 can train one-channel images?

**Comment by 13230668653** [comment]
I also encountered the same problem, how did you solve it?
