### ISSUE TITLE
  Training industrial defect data set

### ISSUE THREAD

**Issue by 202041600047** [CoinCheung/BiSeNet#169]
I want to use this bisenetv2 network to do industrial defect detection. I want to divide the data into defective parts and separate them from the rest. When I trained my own data set, the following problems occurred.
Until now I modified:
bisenetv2.py:
im_root='./datasets/industrial_product',
train_im_anns='./datasets/industrial_product/train.txt',
val_im_anns='./datasets/industrial_product/val.txt',

The files I have changed are mainly for train.py, trains_ amp. py, evaluate. py, demo. py in tools, and cityscapes_cv2.py in lib； bisenetv2, bisenetv1.py in lib/models. Change the number of categories(number of categories is 3) in the above files, and update label_info in cityscapes_cv2.py.
labels_info = [{"hasInstances": False, "category": "void", "catid": 0, "name": "unlabeled", "ignoreInEval": True, "id": 0, "color": [0, 0, 0], "trainId": 0},
    {"hasInstances": False, "category": "void", "catid": 0, "name": "defect", "ignoreInEval": False, "id": 1, "color": [255, 0, 0], "trainId": 1},]

When I run tools.train. py,It has the following error, I don't know how to solve it.

Traceback (most recent call last):
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/train.py", line 249, in <module>
    main()
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/train.py", line 245, in main
    train()
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/train.py", line 188, in train
    for it, (im, lb) in enumerate(dl):
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1179, in _next_data
    return self._process_data(data)
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in DataLoader worker process 3.
Original Traceback (most recent call last):
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caiweixin/Downloads/BiSeNet-master (1)/BiSeNet-master/venv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/base_dataset.py", line 49, in __getitem__
    im_lb = self.trans_func(im_lb)
  File "./lib/base_dataset.py", line 72, in __call__
    im_lb = self.trans_func(im_lb)
  File "./lib/transform_cv2.py", line 150, in __call__
    im_lb = comp(im_lb)
  File "./lib/transform_cv2.py", line 27, in __call__
    assert im.shape[:2] == lb.shape[:2]
AssertionError

 would you like to help me solve this problem? Thank you very much.My email address is 3434875098@qq.com

**Comment by CoinCheung** [comment]
your input image and its associated label image have different size. Please check your dataset.

**Comment by 202041600047** [comment]
> your input image and its associated label image have different size. Please check your dataset.
I thought so at first，but when I debug,  im.shape:(3648, 5472, 3)  lb.shape: (3648, 5472) and im.shape[:2] == lb.shape[:2]  is True,What should I do next? Would you like to help me？

**Comment by 202041600047** [comment]
I have adjusted my dataset to the format of cityscapes, but errors are always reported when running train.py and evaluate.py. I want to divide my defect dataset into two colors. The defect part is white and the background part is black, so I modified cityscapes_ cv2.py, as follows:
labels_info = [
               {"hasInstances": True, "category": "object", "catid": 0, "name": "backforward", "ignoreInEval": False, "id": 0, "color": [0, 0, 0], "trainId": 0},
               {"hasInstances": True, "category": "object", "catid": 0, "name": "defect", "ignoreInEval": False, "id": 1, "color": [255, 255, 255], "trainId": 1},
               {"hasInstances": False, "category": "vehicle", "catid": 7, "name": "license plate", "ignoreInEval": True, "id": -1, "color": [0, 0, 142], "trainId": -1}]
And I'm in train.py and evaluate.py, cityscapes_ cv2.py has modified the number of categories to 2, but I haven't modified others
.The following error occurred when I ran evaluate. py:

setup and restore model
  0%|          | 0/1018 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 294, in <module>
    main()
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 290, in main
    evaluate(cfg, args.weight_pth)
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 262, in evaluate
    heads, mious = eval_model(cfg, net)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 204, in eval_model
    mIOU = single_scale(net, dl, cfg.n_cats)
  File "/home/caiweixin/Downloads/BiSeNet-master (4)/BiSeNet-master/tools/evaluate.py", line 46, in __call__
    for i, (imgs, label) in diter:
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1165, in __iter__
    for obj in iterable:
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/caiweixin/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/base_dataset.py", line 46, in __getitem__
    label = self.lb_map[label]
IndexError: index 2 is out of bounds for axis 0 with size 2

What should I do? thank you

**Comment by CoinCheung** [comment]
Likely your dataset is not purely composed of label 0 and 1.
