### ISSUE TITLE
about the module "inplace_abn"

### ISSUE THREAD

**Issue by jiangolder** [CoinCheung/BiSeNet#17]
I trained the model with **only one GPU**.

When I train the code with "CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=**1** train.py", there are some errors:

```
/home/min/JHW/code/modules/src/inplace_abn_cuda.cu(318): error: no instance of overloaded function "thrust::transform_if" matches the argument list
            argument types are: (<error-type>, thrust::device_ptr<float>, thrust::device_ptr<float>, thrust::device_ptr<float>, lambda [](const float &)->float, lambda [](const float &)->__nv_bool)
          detected during instantiation of "void elu_backward_impl(T *, T *, int64_t) [with T=float]" 
(330): here

12 errors detected in the compilation of "/tmp/tmpxft_00002758_00000000-7_inplace_abn_cuda.cpp1.ii".
ninja: build stopped: subcommand failed.
```

However, when I trained it with “CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --nproc_per_node=**2** train.py”， the traceback is:

```
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from model import BiSeNet
  File "/home/min/JHW/code/model.py", line 10, in <module>
    from resnet import Resnet18
  File "/home/min/JHW/code/resnet.py", line 9, in <module>
    from modules.bn import InPlaceABNSync as BatchNorm2d
  File "/home/min/JHW/code/modules/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "/home/min/JHW/code/modules/bn.py", line 10, in <module>
    from .functions import *
  File "/home/min/JHW/code/modules/functions.py", line 18, in <module>
    extra_cuda_cflags=["--expt-extended-lambda"])
  File "/home/min/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 645, in load
    is_python_module)
  File "/home/min/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 825, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/min/anaconda2/envs/py3/lib/python3.5/site-packages/torch/utils/cpp_extension.py", line 964, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/min/anaconda2/envs/py3/lib/python3.5/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'inplace_abn'
```

So, I am not sure it is because of Ninja or the module inplace_abn. I guess it may related to the version of CUDA and cuDNN (I use 9.0 and 7.4.1).

Thank you for your help!

**Comment by TianMingChen** [comment]
Did you have solve this problem?

**Comment by CoinCheung** [comment]
Closing this, since we do not rely on `inplace-abn` now.
