### ISSUE TITLE
error occurred  when training on multi gpus.

### ISSUE THREAD

**Issue by huaiyuyaya** [CoinCheung/BiSeNet#170]
hello, when I'm trying to using multi gpus for training, I got this error. How could I solve this problem? Thanks.
******:~/Codes/BiseNet$ bash tools/dist_train.sh
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "tools/train_amp.py", line 210, in <module>
    main()
  File "tools/train_amp.py", line 202, in main
    rank=args.local_rank
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 423, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 133, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/CN/wei.dong/anaconda3/envs/bisenet/lib/python3.6/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/CN/wei.dong/anaconda3/envs/bisenet/bin/python', '-u', 'tools/train_amp.py', '--local_rank=1', '--config', 'configs/bisenetv1_city.py']' returned non-zero exit status 1.

**Comment by huangqi111** [comment]
I also encounter problems . how to solve this problem.

**Comment by huaiyuyaya** [comment]
> I also encounter problems . how to solve this problem.
The problem of me is that the port using was occupied by system, changing the port using can solve this problem.
maybe you can try to set port to a another number such as 29510.
