### ISSUE TITLE
when train ,find subprocess.CalledProcessError: Command

### ISSUE THREAD

**Issue by huangqi111** [CoinCheung/BiSeNet#172]
subprocess.CalledProcessError: Command '['/home/user/hq/work/env/torch/bin/python', '-u', 'tools/train_amp.py', '--local_rank=1', '--config', 'configs/bisenetv2_city.py']' returned non-zero exit status 1.
   how to solve this problem？  help help

**Comment by CoinCheung** [comment]
Do you have more specific error information ?

**Comment by huangqi111** [comment]
> Do you have more specific error information ?

Traceback (most recent call last):
  File "tools/train.py", line 226, in <module>
    main()
  File "tools/train.py", line 217, in main
    rank=args.local_rank
  File "/home/user/hq/work/env/torch/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 500, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/user/hq/work/env/torch/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 138, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
Killing subprocess 30485
Traceback (most recent call last):
  File "/home/user/hq/work/env/torch/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/hq/work/env/torch/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/hq/work/env/torch/lib/python3.6/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/user/hq/work/env/torch/lib/python3.6/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/user/hq/work/env/torch/lib/python3.6/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/hq/work/env/torch/bin/python', '-u', 'tools/train.py', '--local_rank=0']' returned non-zero exit status 1.

**Comment by CoinCheung** [comment]
The port is occupied, maybe you can change a port to use to train your model.
For example, you can add an option of `--port 33221` to set the port to be 33221.

**Comment by huangqi111** [comment]
when I train，The program does not respond，


COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
python  17435 user   14u  IPv4 11581572      0t0  TCP *:3322 (LISTEN)
python  17435 user   17u  IPv4 11581574      0t0  TCP localhost:59396->localhost:3322 (ESTABLISHED)
python  17435 user   18u  IPv4 11562821      0t0  TCP localhost:3322->localhost:59396 (ESTABLISHED)
(/home/user/hq/work/env/torch) user@user-C299:~/hq/code/BiSeNet-master$ kill -9 17435
(/home/user/hq/work/env/torch) user@user-C299:~/hq/code/BiSeNet-master$ python -m torch.distributed.launch --nproc_per_node=1 tools/train_amp.py --config configs/bisenetv2_city.py

**Comment by CoinCheung** [comment]
What is you configuration of your platform? Please add `CUDA_VISIBLE_DEVICES=0` to assign gpu, if you have multi-gpu on your server and you would like to use only one gpu.

**Comment by huangqi111** [comment]
one GPU,how to train？

**Comment by CoinCheung** [comment]
You did not post your platform and environment configuration. Maybe you have solved it now, it is more likely to be a problem about pytorch usage, so I am closing this. Leave a message if you need more discussions.
