### ISSUE TITLE
Tensor size error when inferencing on odd resolution images

### ISSUE THREAD

**Issue by matialmar** [CoinCheung/BiSeNet#221]
Error:
```
Traceback (most recent call last):
  File "tools/demo.py", line 46, in <module>
    out = net(im).squeeze().detach().cpu().numpy()
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 335, in forward
    feat_head = self.bga(feat_d, feat_s)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "./lib/models/bisenetv2.py", line 277, in forward
    left = left1 * torch.sigmoid(right1)
RuntimeError: The size of tensor a (54) must match the size of tensor b (56) at non-singleton dimension 2
```

Steps to replicate:
Inference using COCO weights on an image with odd resolution (e.g. 640x427px)
example image: 000000000885.jpg in 2017 coco validation dataset

Possible source of error:
x_d.size()[2:] in method forward on class BGALayer
size = x.size()[2:] in method forward on class BiSeNetV2

**Comment by CoinCheung** [comment]
Hi,

You should resize the input image to a muliply of 32, before feeding it into the model.
