### ISSUE TITLE
Question for Bisenet

### ISSUE THREAD

**Issue by Hekeshi** [CoinCheung/BiSeNet#26]
Hi cheung

1. When I run the command python evaluate.py,  you could see the errors as follows:

Blade:~/BiSeNet-master$ python evaluate.py
Traceback (most recent call last):
  File "evaluate.py", line 5, in <module>
    from model import BiSeNet
  File "/home/keshi/BiSeNet-master/model.py", line 8, in <module>
    import torchvision
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: /home/keshi/anaconda3/lib/python3.7/site-packages/torchvision/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN2at7getTypeERKNS_6TensorE

Do you tell me the version of torchvision module and ubuntu you used? 

2. When I run the command python diss/evaluate.py,  you could see the errors as follows:
keshi@keshi-Blade:~/BiSeNet-master$ python diss/evaluate.py                                                                                  
Traceback (most recent call last):                                                                                                                  
  File "diss/evaluate.py", line 4, in <module>                                                                                                      
    from logger import setup_logger                                                                                                                 
ImportError: cannot import name 'setup_logger' from 'logger' (/home/keshi/anaconda3/lib/python3.7/site-packages/logger/__init__.py) 

I do not why it will happen? Could you tell me the reason?

**Comment by CoinCheung** [comment]
1. You are using a new version of torchvision, please try a older version.

2. You have installed some package named logger, which confused the importing behavior, since I tried to import the `logger.py` from this repository rather than from other packages.
