### ISSUE TITLE
evaluate error

### ISSUE THREAD

**Issue by Lee6384** [CoinCheung/BiSeNet#271]
Hello,thanks for your great work! I used them to get through my training. But in the evaluate stage, something is wrong:

/home/dell/anaconda3/envs/Faster/bin/python3.8 /home/dell/lz/codes/BiSeNet-master/tools/evaluate.py
setup and restore model
compute single scale metrics
  0%|          | 0/250 [00:00<?, ?it/s]/home/dell/anaconda3/envs/Faster/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
100%|██████████| 250/250 [00:44<00:00,  5.59it/s]
Traceback (most recent call last):
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 453, in <module>
    main()
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 449, in main
    evaluate(cfg, args.weight_pth)
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 424, in evaluate
    iou_heads, iou_content, f1_heads, f1_content = eval_model(cfg, net)
  File "/home/dell/anaconda3/envs/Faster/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 329, in eval_model
    metrics = single_scale(net, dl)
  File "/home/dell/anaconda3/envs/Faster/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 174, in __call__
    metric_dict = self.metric_observer.compute_metrics()
  File "/home/dell/anaconda3/envs/Faster/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/lz/codes/BiSeNet-master/tools/evaluate.py", line 93, in compute_metrics
    miou = ious.nanmean()
AttributeError: 'Tensor' object has no attribute 'nanmean'

Process finished with exit code 1

I don't know why there is such a mistake, and I didn't change the code, but I can't find the problem,could you please tell me why? thanks.

**Comment by simplew2011** [comment]
# miou = ious.nanmean()
        miou = ious[ious < float('inf')].mean()
