### ISSUE TITLE
question about finetune.

### ISSUE THREAD

**Issue by so45jj45** [CoinCheung/BiSeNet#277]
How do I finetune the bisenetv2_ade20k model with a coco dataset?

**Comment by so45jj45** [comment]
I used this code 
torchrun tools/train_amp.py --finetune-from models/model_final_v2_ade20k.pth --config configs/ade20k_to_coco.py

ade20k_to_coco

cfg = dict(
    model_type='bisenetv2',
    n_cats=150,
    num_aux_heads=4,
    lr_start=5e-3,
    weight_decay=1e-4,
    warmup_iters=1000,
    max_iter=180000,
    dataset='CocoStuff',
    im_root='./datasets/coco',
    train_im_anns='./datasets/coco/train.txt',
    val_im_anns='./datasets/coco/val.txt',
    scales=[0.75, 2.],
    cropsize=[640, 640],
    eval_crop=[640, 640],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=2,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)

and got this error

Traceback (most recent call last):
  File "tools/train_amp.py", line 206, in <module>
    main()
  File "tools/train_amp.py", line 202, in main
    train()
  File "tools/train_amp.py", line 156, in train
    loss_pre = criteria_pre(logits, lb)
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "./lib/ohem_ce_loss.py", line 38, in forward
    loss_hard = loss[loss > self.thresh]
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 11522) of binary: /home/ai1/anaconda3/envs/bise/bin/python
Traceback (most recent call last):
  File "/home/ai1/anaconda3/envs/bise/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
tools/train_amp.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-23_11:04:05
  host      : Ai1
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 11522)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 11522

**Comment by CoinCheung** [comment]
cocostuff has 171 categories not 150.

**Comment by so45jj45** [comment]
Thanks for fast reply

I changed the categories 150 to 171 in config

ade20k_to_coco.py

cfg = dict(
    model_type='bisenetv2',
    n_cats=171,
    num_aux_heads=4,
    lr_start=5e-3,
    weight_decay=1e-4,
    warmup_iters=1000,
    max_iter=180000,
    dataset='CocoStuff',
    im_root='./datasets/coco',
    train_im_anns='./datasets/coco/train.txt',
    val_im_anns='./datasets/coco/val.txt',
    scales=[0.75, 2.],
    cropsize=[640, 640],
    eval_crop=[640, 640],
    eval_scales=[0.5, 0.75, 1, 1.25, 1.5, 1.75],
    ims_per_gpu=2,
    eval_ims_per_gpu=1,
    use_fp16=True,
    use_sync_bn=True,
    respth='./res',
)


but i got error


Traceback (most recent call last):
  File "tools/train_amp.py", line 206, in <module>
    main()
  File "tools/train_amp.py", line 202, in main
    train()
  File "tools/train_amp.py", line 127, in train
    net, criteria_pre, criteria_aux = set_model(dl.dataset.lb_ignore)
  File "tools/train_amp.py", line 58, in set_model
    net.load_state_dict(torch.load(args.finetune_from, map_location='cpu'))
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BiSeNetV2:
	size mismatch for head.conv_out.1.weight: copying a param with shape torch.Size([150, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([171, 1024, 1, 1]).
	size mismatch for head.conv_out.1.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([171]).
	size mismatch for aux2.conv_out.1.weight: copying a param with shape torch.Size([150, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([171, 16, 1, 1]).
	size mismatch for aux2.conv_out.1.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([171]).
	size mismatch for aux3.conv_out.1.weight: copying a param with shape torch.Size([150, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([171, 64, 1, 1]).
	size mismatch for aux3.conv_out.1.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([171]).
	size mismatch for aux4.conv_out.1.weight: copying a param with shape torch.Size([150, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([171, 256, 1, 1]).
	size mismatch for aux4.conv_out.1.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([171]).
	size mismatch for aux5_4.conv_out.1.weight: copying a param with shape torch.Size([150, 1024, 1, 1]) from checkpoint, the shape in current model is torch.Size([171, 1024, 1, 1]).
	size mismatch for aux5_4.conv_out.1.bias: copying a param with shape torch.Size([150]) from checkpoint, the shape in current model is torch.Size([171]).
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 18346) of binary: /home/ai1/anaconda3/envs/bise/bin/python
Traceback (most recent call last):
  File "/home/ai1/anaconda3/envs/bise/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ai1/anaconda3/envs/bise/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/train_amp.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-11-23_18:33:46
  host      : Ai1
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 18346)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================



I would appreciate it if you let me know if you know the solution.

**Comment by CoinCheung** [comment]
Hi,

You should set `strict=False` here:
https://github.com/CoinCheung/BiSeNet/blob/b5fa169d522cf8d9e6219559e26d2f9c618fa4fd/tools/train_amp.py#L58
set for the method of `load_state_dict`.

**Comment by CoinCheung** [comment]
Likely you have solved this. I have updated a bit about this, and I am closing this.
