### ISSUE TITLE
windows下应该怎么训练？

### ISSUE THREAD

**Issue by t973288913** [CoinCheung/BiSeNet#321]
C:\Users\97328\.conda\envs\torch\python.exe "E:\A_Deep learning model\BiSeNet\tools\train_amp.py" 
Traceback (most recent call last):
  File "E:\A_Deep learning model\BiSeNet\tools\train_amp.py", line 210, in <module>
    main()
  File "E:\A_Deep learning model\BiSeNet\tools\train_amp.py", line 200, in main
    local_rank = int(os.environ['LOCAL_RANK'])
  File "C:\Users\97328\.conda\envs\torch\lib\os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'

**Comment by 1404561326521** [comment]
你好，请问解决这个问题吗
