### ISSUE TITLE
SyncBatchNorm is only supported within torch.nn.parallel.DistributedDataParallel

### ISSUE THREAD

**Issue by Shelfcol** [CoinCheung/BiSeNet#53]
I just ran the demo.py
python3 demo.py --ckpt res/model_final.pth --img_path ./pic.jpg
Traceback (most recent call last):
  File "demo.py", line 43, in <module>
    out = net(im)[0].argmax(dim=1).squeeze().detach().cpu().numpy()
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gxf/deeplearning/BiSeNet-1/fp16/model.py", line 248, in forward
    feat_cp8, feat_cp16 = self.cp(x)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gxf/deeplearning/BiSeNet-1/fp16/model.py", line 112, in forward
    feat8, feat16, feat32 = self.resnet(x)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gxf/deeplearning/BiSeNet-1/fp16/resnet.py", line 77, in forward
    x = self.bn1(x)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 430, in forward
    raise AttributeError('SyncBatchNorm is only supported within torch.nn.parallel.DistributedDataParallel')
AttributeError: SyncBatchNorm is only supported within torch.nn.parallel.DistributedDataParallel

my torch version is 1.2.0
Can anyone met this problem?Thanks.

**Comment by CoinCheung** [comment]
Sorry, it was my fault, I did not check before pushing it. I has pushed a fix, you may have a try. Please leave a message if there is still problems.

**Comment by Shelfcol** [comment]
I just downloaded your repo again, but I still got this error.What should I do?

**Comment by CoinCheung** [comment]
That is weird, it works on my computer, what is the output by running the command `head -n 20 fp16/model.py` ? 

And did you try to train the model with `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 fp16/train.py`? I you trained with  `CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 train.py`, you will have to change the line of `from fp16.model import BiSeNet` to `from model import BiSeNet` in the script of `demo.py`.

**Comment by Shelfcol** [comment]
I found your latest commit are several months ago, are you sure you have pushed already?

And error(my PC only have one GPU ):

CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.launch --nproc_per_node=2 fp16/train.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "fp16/train.py", line 10, in <module>
    from fp16.evaluate import evaluate
  File "./fp16/evaluate.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "fp16/train.py", line 10, in <module>
    from fp16.evaluate import evaluate
  File "./fp16/evaluate.py", line 19, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
Traceback (most recent call last):
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/home/gxf/anaconda3/envs/tf1.4.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/gxf/anaconda3/envs/tf1.4.1/bin/python3', '-u', 'fp16/train.py', '--local_rank=1']' returned non-zero exit status 1.

**Comment by CoinCheung** [comment]
have you tried to install `tqdm`? you need to install it: `python -m pip install tqdm`, and other dependencies, such as `apex`.

**Comment by Shelfcol** [comment]
I followed your advise and changed the line of from fp16.model import BiSeNet to from model import BiSeNet in the script of demo.py.
demo.py  worked, thx

**Comment by CoinCheung** [comment]
OK, then I am closing this.
