### ISSUE TITLE
I have a problem when I trained with cityscapes dataset. Could you give some suggestions?

### ISSUE THREAD

**Issue by CoolLoveBoy** [CoinCheung/BiSeNet#64]
$ python -m torch.distributed.launch --nproc_per_node=2 bisenetv2/train.py --fp16
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
Traceback (most recent call last):
  File "bisenetv2/train.py", line 20, in <module>
  File "bisenetv2/train.py", line 20, in <module>
        from bisenetv2.cityscapes_cv2 import get_data_loader
from bisenetv2.cityscapes_cv2 import get_data_loader
  File "./bisenetv2/cityscapes_cv2.py", line 14, in <module>
  File "./bisenetv2/cityscapes_cv2.py", line 14, in <module>
        import bisenetv2.transform_cv2 as T
import bisenetv2.transform_cv2 as T
ImportErrorImportError: : No module named transform_cv2No module named transform_cv2

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/coollove/.local/lib/python2.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/home/coollove/.local/lib/python2.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', u'-u', 'bisenetv2/train.py', u'--local_rank=1', '--fp16']' returned non-zero exit status 1

**Comment by CoinCheung** [comment]
Hi, please use python3(better python3.6 which is the version I used) and try again.

**Comment by CoinCheung** [comment]
I have been too late and maybe you have figured it out, I am closing this.

**Comment by Flyzanetothesky** [comment]
Hi, CoolLoveBoy. I meet with same question，how do you  solve it ? please
