### ISSUE TITLE
dataload problem

### ISSUE THREAD

**Issue by TianMingChen** [CoinCheung/BiSeNet#67]
hi,what can i do for thos problem?
int class RandomResizedCrop(object):
im = np.pad(im, ((pad_h, pad_h), (pad_w, pad_w), (0, 0)))

![image](https://user-images.githubusercontent.com/20785298/86569851-a1001b00-bfa1-11ea-8221-d8d733595a37.png)

**Comment by TianMingChen** [comment]
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./bisenetv2/cityscapes_cv2.py", line 117, in __getitem__
    im_lb = self.trans_func(im_lb)
  File "./bisenetv2/cityscapes_cv2.py", line 140, in __call__
    im_lb = self.trans_func(im_lb)
  File "./bisenetv2/transform_cv2.py", line 149, in __call__
    im_lb = comp(im_lb)
 File "./bisenetv2/transform_cv2.py", line 42, in __call__
    im = np.pad(im, ((pad_h, pad_h), (pad_w, pad_w), 'constant', (0, 0)))
TypeError: pad() missing 1 required positional argument: 'mode'

**Comment by CoinCheung** [comment]
Sorry for being so late. Have you figured out your problem? If you, please use `numpy` of version 1.17, and try again.

**Comment by CoinCheung** [comment]
Closing this since you may have solved this.
