### ISSUE TITLE
SyncBatchNorm is only supported within torch.nn.parallel.DistributedDataParallel

### ISSUE THREAD

**Issue by dzyjjpy** [CoinCheung/BiSeNet#70]
run demo.py as described in reade,  errors with syncbn.  Does anyone have similar errors?
@CoinCheung Thanks

Traceback (most recent call last):
  File "/home/jiapy/workspace/segmentation/BiSeNet/demo.py", line 36, in <module>
    output_device=0     # output_device=args.local_rank
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/torch/nn/parallel/distributed.py", line 268, in __init__
    self.process_group = _get_default_group()
  File "/home/jiapy/virtualEnv/py3.6torch1.2/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 273, in _get_default_group
    raise RuntimeError("Default process group has not been initialized, "
**RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.**

Process finished with exit code 1

**Comment by dzyjjpy** [comment]
pytorch is:  1.1 or 1.2

**Comment by CoinCheung** [comment]
Hi,

I have refactored the code, please have a try following the new readme and see if there are still problems.

**Comment by CoinCheung** [comment]
I am closing this, you  can still leave a message to communicate.
