### ISSUE TITLE
How to use single GPU training for refactored code

### ISSUE THREAD

**Issue by cherrysnowy** [CoinCheung/BiSeNet#87]

**Comment by CoinCheung** [comment]
Just do this:
```
$ export CUDA_VISIBLE_DEVICES=0
$ python -m torch.distributed.launch --nproc_per_node=1 tools/train.py --model bisenetv2 # or bisenetv1
```

**Comment by cherrysnowy** [comment]
The error generated after running the above command：subprocess.CalledProcessError: Command '['/home/star/miniconda3/envs/torch/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv2']' returned non-zero exit status 1.

**Comment by CoinCheung** [comment]
Would you please print the whole error message ?

**Comment by cherrysnowy** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 247, in <module>
    main()
  File "tools/train.py", line 239, in main
    dist.init_process_group(
TypeError: init_process_group() missing 1 required positional argument: 'backend'
Traceback (most recent call last):
  File "/home/star/miniconda3/envs/torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/star/miniconda3/envs/torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/star/miniconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/star/miniconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/star/miniconda3/envs/torch/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv2']' returned non-zero exit status 1.

**Comment by cherrysnowy** [comment]
File "tools/train.py", line 233
    dist.init_process_group(
    ^
IndentationError: unexpected indent
Traceback (most recent call last):
  File "/home/star/miniconda3/envs/torch/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/star/miniconda3/envs/torch/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/star/miniconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/star/miniconda3/envs/torch/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/star/miniconda3/envs/torch/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv2']' returned non-zero exit status 1.

This is the error after rerun.

**Comment by CoinCheung** [comment]
Are you using my original script ?  The `tools/train.py` has only 225 lines of code, how can the error message show that the error lies in line 233 ?
