### ISSUE TITLE
TypeError: pad() missing 1 required positional argument: 'mode'

### ISSUE THREAD

**Issue by wind19970924** [CoinCheung/BiSeNet#88]
/home/nvidia/anaconda3/envs/pytorch-2/bin/python /home/nvidia/yuyi/BiSeNet-master/tools/train.py
/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/cuda/__init__.py:125: UserWarning: 
GeForce RTX 2080 with CUDA capability sm_75 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 compute_37.
If you want to use the GeForce RTX 2080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "/home/nvidia/yuyi/BiSeNet-master/tools/train.py", line 225, in <module>
    main()
  File "/home/nvidia/yuyi/BiSeNet-master/tools/train.py", line 221, in main
    train()
  File "/home/nvidia/yuyi/BiSeNet-master/tools/train.py", line 164, in train
    for it, (im, lb) in enumerate(dl):
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nvidia/anaconda3/envs/pytorch-2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nvidia/yuyi/BiSeNet-master/lib/base_dataset.py", line 48, in __getitem__
    im_lb = self.trans_func(im_lb)
  File "/home/nvidia/yuyi/BiSeNet-master/lib/base_dataset.py", line 71, in __call__
    im_lb = self.trans_func(im_lb)
  File "/home/nvidia/yuyi/BiSeNet-master/lib/transform_cv2.py", line 150, in __call__
    im_lb = comp(im_lb)
  File "/home/nvidia/yuyi/BiSeNet-master/lib/transform_cv2.py", line 42, in __call__
    im = np.pad(im, ((pad_h, pad_h), (pad_w, pad_w), (0, 0)))
TypeError: pad() missing 1 required positional argument: 'mode'

help.... thanks a lot

**Comment by CoinCheung** [comment]
What is your numpy version ? I am using 1.17.

**Comment by wind19970924** [comment]
1.19，我改为1.17试试，多谢

**Comment by CoinCheung** [comment]
Close this since you might have figured it out.
