### ISSUE TITLE
Train without multiple GPUs

### ISSUE THREAD

**Issue by QasimKhan5x** [CoinCheung/BiSeNet#92]
I only have one GPU in my system. I have followed your instruction in #87 and issued this command:
`$ export CUDA_VISIBLE_DEVICES=0`
`$ python -m torch.distributed.launch --nproc_per_node=1 tools/train.py --model bisenetv2 # or bisenetv1`

However, I am getting these errors:
Traceback (most recent call last):
  File "tools/train.py", line 225, in <module>
    main()
  File "tools/train.py", line 221, in main
    train()
  File "tools/train.py", line 164, in train
    for it, (im, lb) in enumerate(dl):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "./lib/base_dataset.py", line 43, in __getitem__
    img, label = cv2.imread(impth)[:, :, ::-1], cv2.imread(lbpth, 0)
TypeError: 'NoneType' object is not subscriptable

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'tools/train.py', '--local_rank=0', '--model', 'bisenetv2']' returned non-zero exit status 1.

**Comment by TianchaoHuo** [comment]
Excuse me. I meet the same problems. could you tell me how to solve it?

**Comment by QasimKhan5x** [comment]
@TianchaoHuo I got this problem because cityscapes_cv2.py was not reading my custom dataset files. So you would have to modify cityscapes_cv2.py and base_dataset.py according to your needs

**Comment by CuttlefishXuan** [comment]
Hi, I meet the same question, but I am using the original cityscapes datasets. I don't know where is the problem, anyone can help me?
